### ISSUE TITLE
Visualizing data for QC purposes

### ISSUE THREAD

**Issue by camilavargasp** [njlyon0/collab_vargas-quality-control-talk#1]
- Here is the link to the [7 Basic Quality Tools with R](https://towardsdatascience.com/7-basic-tools-of-quality-using--r-49fef5481e07) shared by Chris.
- We probably don't need to include this, especially if we are not familiar with these tools but could be worth mentioning in the **When to plot data?** sections.

**Comment by njlyon0** [comment]
Added this link to the README for ease of access (see this commit: https://github.com/njlyon0/collab_vargas-quality-control-talk/commit/2a1daea557dfc59efaa7061c7b6cda84eb9686b0)
